"""Paper-ready significance table: DLF vs every one of the 47 configurations of Table 3 (tab:DLF).

    cd binary-classifier && python -m baselines.sigtable      # -> paper/tables/tab_significance.tex (+ .md)

Input: significance_dlf_full_ftchar_gpt4omini_table3.csv, i.e. `python -m baselines.significance --ref
dlf_full_l1w12_fasttext_char_gpt-4o-mini --include <the 47 Table-3 systems + DLF> --suffix _table3`.
Test: paired bootstrap over the 5,166 test messages (10,000 resamples) of the macro-F1 difference DLF - method,
two-sided p-values, Holm-corrected over the 47 comparisons. Rows follow the order and grouping of Table 3.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from .table3 import GROUPS

T = Path(__file__).resolve().parents[2] / "paper" / "tables"
SRC = T / "significance_dlf_full_ftchar_gpt4omini_table3.csv"


def fmt_p(p: float) -> str:
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def main():
    df = pd.read_csv(SRC).set_index("key")
    assert len(df) == 47, f"expected the 47 Table-3 configurations, got {len(df)}"
    dlf_f1 = float(df["macro_f1"].iloc[0] + df["d_macro_f1"].iloc[0])  # DLF macro-F1 = method + delta
    n_better = int(((df.p_macro_f1_holm < .05) & (df.d_macro_f1 > 0)).sum())
    n_worse = int(((df.p_macro_f1_holm < .05) & (df.d_macro_f1 < 0)).sum())
    n_tie = len(df) - n_better - n_worse

    tex = [r"\begin{table}[h]", r"\centering",
           r"\caption{Pairwise comparison of DLF with each filtering method using paired bootstrap tests with Holm "
           r"correction, showing that DLF significantly outperforms " + (f"all {n_better}" if n_better == len(df) else f"{n_better} of {len(df)}")
           + r" configurations. Gain is the F1 difference between DLF and the method, with its 95\% confidence interval.}",
           r"\label{tab:significance}", r"\resizebox{\columnwidth}{!}{%", r"\begin{tabular}{@{}llccc@{}}", r"\toprule",
           r"\textbf{Embedding} & \textbf{Classifier} & \textbf{F1} & \textbf{DLF's F1 gain} (95\% CI) & \textbf{$p$-value} \\",
           r"\midrule"]
    md = [f"DLF macro-F1 = {dlf_f1:.3f}; DLF significantly better than {n_better}/47, tied {n_tie}, worse {n_worse} "
          f"(paired bootstrap, Holm over 47).", "", "| Embedding | Classifier | F1 | DLF's F1 gain (95% CI) | p (Holm) |", "|---|---|---|---|---|"]
    seen = 0
    for g, items in GROUPS:
        rows = [(Path(path).name, lab) for path, lab in items if Path(path).name in df.index]
        for i, (key, lab) in enumerate(rows):
            r = df.loc[key]
            first = (rf"\multirow{{{len(rows)}}}{{*}}{{{g}}}" if len(rows) > 1 else g) if i == 0 else ""
            ci = f"{r.d_macro_f1:+.3f} [{r.lo_macro_f1:.3f}, {r.hi_macro_f1:.3f}]"
            tex.append(f"{first} & {lab} & {r.macro_f1:.3f} & {ci} & {fmt_p(r.p_macro_f1_holm)} \\\\")
            md.append(f"| {g if i == 0 else ''} | {lab.replace('$n$', 'n')} | {r.macro_f1:.3f} | {ci} | {r.p_macro_f1_holm:.4f} |")
            seen += 1
        if rows:
            tex.append(r"\midrule")
    assert seen == 47, f"only {seen} of 47 rows matched Table 3"
    tex.append(rf"\textbf{{DLF}} & \textbf{{fastText + gpt-4o-mini}} & \textbf{{{dlf_f1:.3f}}} & -- & -- \\")
    tex.append(r"\bottomrule")
    tex += [r"\end{tabular}%", "}", r"\end{table}"]
    (T / "tab_significance.tex").write_text("% AUTO-GENERATED by binary-classifier/baselines/sigtable.py\n" + "\n".join(tex) + "\n")
    (T / "tab_significance.md").write_text("\n".join(md) + "\n")
    print("\n".join(md[:6] + ["..."] + md[-4:]))


if __name__ == "__main__":
    main()
